### ISSUE TITLE
v1.0.2 | Al clickear en el magnet todas las pruebas me dieron "undefined".

### ISSUE THREAD

**Issue by eliooses** [bitumin/magneto#1]
La búsqueda sale con los resultados de forma perfecta y el mensaje de copiado exitoso aparece, pero el clipboard solo recibe un "undefined" con todas las pruebas que realice.

**Comment by bitumin** [comment]
Buenas @eliooses . El bug reportado debería estar corregido en la [v1.1.0](https://github.com/bitumin/magneto/releases/tag/v1.1.0) .
